# This is a basic workflow to help you get started with Actions

name: yaml-poc

on:
  push:
    branches: [ main ]
  

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
         
            
      - name: Build with Maven
        run: mvn clean install   
        
      - name: Status of POC
        run: echo hello world
