# This is a basic workflow to help you get started with Actions

name: Worfklow for Spring boot application to be deployed on Azure VM

on:
  push:
    branches: [ dev ]
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: package application
        run: mvn package
      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}        
          username: ${{ secrets.AZURE_USERNAME }}      
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          source: "my-app.jar"      
          target: "~/source"
      - name: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_ADDRESS }}        
          username: ${{ secrets.AZURE_USERNAME }}      
          key: ${{ secrets.SSH_SECRET }}
          port: 22
          script: |
                sudo /etc/init.d/my-app stop
                mv ~/source/my-app.jar ~/source/my-app-old.jar
                mv ~/source/my-app-latest.jar ~/source/my-app.jar
                sudo rm -rf /etc/init.d/my-app
                sudo ln -s -f ~/source/my-app.jar /etc/init.d/my-app
                sudo /etc/init.d/my-app start
                rm ~/source/my-app-old.jar
